import bcrypt from 'bcryptjs';
import mongoose from 'mongoose';

const data = {
  users: [
    {
      name: 'Kiko',
      email: 'kiko@gmail.com',
      password: bcrypt.hashSync('12', 8),
      isSeller: true,
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'john@example.com',
      password: bcrypt.hashSync('1234', 8),
      isSeller: true,
      isAdmin: false,
    },
    {
      name: 'Jane',
      email: 'jane@example.com',
      password: bcrypt.hashSync('1234', 8),
      isSeller: true,
      isAdmin: false,
    },
    {
      name: 'Kevin',
      email: 'kevin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isSeller: false,
      isAdmin: false,
    },
    {
      name: 'Mark',
      email: 'mark@example.com',
      password: bcrypt.hashSync('1234', 8),
      isSeller: false,
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/img/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      seller: mongoose.Types.ObjectId('5ff6045d3ed3bc60e3fb4f9a'),
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/img/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      seller: mongoose.Types.ObjectId('5ff6045d3ed3bc60e3fb4f9a'),
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/img/p3.jpg',
      price: 220,
      countInStock: 12,
      brand: 'Lacoste',
      rating: 2.8,
      numReviews: 17,
      description: 'high quality product',
      seller: mongoose.Types.ObjectId('5ff6045d3ed3bc60e3fb4f9a'),
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/img/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
      seller: mongoose.Types.ObjectId('5ff6045d3ed3bc60e3fb4f9b'),
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/img/p5.jpg',
      price: 65,
      countInStock: 20,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      seller: mongoose.Types.ObjectId('5ff6045d3ed3bc60e3fb4f9b'),
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/img/p6.jpg',
      price: 139,
      countInStock: 10,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 15,
      description: 'high quality product',
      seller: mongoose.Types.ObjectId('5ff6045d3ed3bc60e3fb4f9c'),
    },
  ],
};
export default data;
